const fs = require("node:fs/promises");
const path = require("node:path");

const CONTRACTS = ["IPRegistry", "LicenseAgreement", "CollaborativeWork"];

const CONTRACTS_ROOT = process.cwd();
const ARTIFACTS_DIR = path.join(CONTRACTS_ROOT, "artifacts", "contracts");
const SHARED_ROOT = path.resolve(CONTRACTS_ROOT, "..", "packages", "contract-artifacts");
const ABI_DIR = path.join(SHARED_ROOT, "abi");
const ADDRESSES_PATH = path.join(SHARED_ROOT, "addresses", "amoy.json");
const INDEX_JS_PATH = path.join(SHARED_ROOT, "index.js");
const INDEX_D_TS_PATH = path.join(SHARED_ROOT, "index.d.ts");

async function ensureSharedStructure() {
  await fs.mkdir(path.join(SHARED_ROOT, "abi"), { recursive: true });
  await fs.mkdir(path.join(SHARED_ROOT, "addresses"), { recursive: true });
}

async function ensureDefaultAddressesFile() {
  try {
    const raw = await fs.readFile(ADDRESSES_PATH, "utf-8");
    JSON.parse(raw);
  } catch {
    const defaultPayload = {
      chainId: 80002,
      network: "amoy",
      deployedAt: null,
      contracts: {
        IPRegistry: "",
        LicenseAgreement: "",
        CollaborativeWork: "",
      },
    };
    await fs.writeFile(ADDRESSES_PATH, JSON.stringify(defaultPayload, null, 2) + "\n", "utf-8");
  }
}

async function exportContractAbis() {
  const exported = {};

  for (const contractName of CONTRACTS) {
    const artifactPath = path.join(
      ARTIFACTS_DIR,
      `${contractName}.sol`,
      `${contractName}.json`,
    );
    const artifactRaw = await fs.readFile(artifactPath, "utf-8");
    const artifact = JSON.parse(artifactRaw);

    exported[contractName] = artifact.abi;

    const abiPath = path.join(ABI_DIR, `${contractName}.json`);
    await fs.writeFile(abiPath, JSON.stringify(artifact.abi, null, 2) + "\n", "utf-8");
  }

  return exported;
}

async function writeIndexFiles(abis) {
  const addresses = JSON.parse(await fs.readFile(ADDRESSES_PATH, "utf-8"));

  const indexJs = `// Auto-generated by contracts/scripts/export-abis.js\n\nexport const CHAIN_ID_AMOY = 80002;\n\nexport const AMOY_ADDRESSES = ${JSON.stringify(addresses, null, 2)};\n\nexport const IPRegistryABI = ${JSON.stringify(abis.IPRegistry, null, 2)};\n\nexport const LicenseAgreementABI = ${JSON.stringify(abis.LicenseAgreement, null, 2)};\n\nexport const CollaborativeWorkABI = ${JSON.stringify(abis.CollaborativeWork, null, 2)};\n`;

  const indexTypes = `export declare const CHAIN_ID_AMOY: number;\n\nexport interface AmoyAddressPayload {\n  chainId: number;\n  network: \"amoy\";\n  deployedAt: string | null;\n  contracts: {\n    IPRegistry: string;\n    LicenseAgreement: string;\n    CollaborativeWork: string;\n  };\n}\n\nexport declare const AMOY_ADDRESSES: AmoyAddressPayload;\nexport declare const IPRegistryABI: readonly unknown[];\nexport declare const LicenseAgreementABI: readonly unknown[];\nexport declare const CollaborativeWorkABI: readonly unknown[];\n`;

  await fs.writeFile(INDEX_JS_PATH, indexJs, "utf-8");
  await fs.writeFile(INDEX_D_TS_PATH, indexTypes, "utf-8");
}

async function main() {
  await ensureSharedStructure();
  await ensureDefaultAddressesFile();
  const abis = await exportContractAbis();
  await writeIndexFiles(abis);
  console.log("Exported contract ABIs to packages/contract-artifacts");
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});

