# Generated by Django 4.2.7 on 2026-03-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0002_step9_receipt_idempotency_key'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='licensepurchase',
            name='licensing_unique_tx_hash',
        ),
        migrations.RemoveConstraint(
            model_name='licensepurchase',
            name='licensing_unique_receipt_idempotency_key',
        ),
        migrations.AddConstraint(
            model_name='licensepurchase',
            constraint=models.UniqueConstraint(condition=models.Q(('tx_hash', ''), _negated=True), fields=('tx_hash',), name='licensing_unique_tx_hash'),
        ),
        migrations.AddConstraint(
            model_name='licensepurchase',
            constraint=models.UniqueConstraint(condition=models.Q(('receipt_idempotency_key', ''), _negated=True), fields=('receipt_idempotency_key',), name='licensing_unique_receipt_idempotency_key'),
        ),
    ]
