# Generated by Django 4.2.7 on 2026-03-23 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('works', '0004_step7_blockchain_registration_fields_and_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('licensing', '0002_step9_receipt_idempotency_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING_APPROVAL', 'Pending approval'), ('APPROVED', 'Approved'), ('BLOCKCHAIN_REGISTRATION_PENDING', 'Blockchain registration pending'), ('REGISTERED', 'Registered'), ('BLOCKCHAIN_REGISTRATION_FAILED', 'Blockchain registration failed')], default='PENDING_APPROVAL', max_length=40)),
                ('blockchain_tx_hash', models.CharField(blank=True, default='', max_length=66)),
                ('blockchain_block_number', models.BigIntegerField(blank=True, null=True)),
                ('blockchain_registered_at', models.DateTimeField(blank=True, null=True)),
                ('blockchain_error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_collaborations', to=settings.AUTH_USER_MODEL)),
                ('work', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collaboration', to='works.creativework')),
            ],
            options={
                'db_table': 'collaboration_collaboration',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollaborationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=42)),
                ('split_bps', models.PositiveIntegerField()),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved')], default='PENDING', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collaboration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='collaboration.collaboration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collaboration_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'collaboration_member',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RevenueSplitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_event', models.CharField(choices=[('LICENSE_PURCHASE', 'License purchase')], max_length=32)),
                ('split_bps', models.PositiveIntegerField()),
                ('amount_wei', models.BigIntegerField()),
                ('tx_hash', models.CharField(blank=True, default='', max_length=66)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collaboration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revenue_records', to='collaboration.collaboration')),
                ('license_purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collaboration_revenue_records', to='licensing.licensepurchase')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revenue_records', to='collaboration.collaborationmember')),
            ],
            options={
                'db_table': 'collaboration_revenue_split_record',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='revenuesplitrecord',
            constraint=models.UniqueConstraint(fields=('license_purchase', 'member'), name='collab_unique_license_member_revenue_record'),
        ),
        migrations.AddConstraint(
            model_name='revenuesplitrecord',
            constraint=models.CheckConstraint(check=models.Q(('split_bps__gte', 1), ('split_bps__lte', 10000)), name='collab_revenue_split_bps_range'),
        ),
        migrations.AddConstraint(
            model_name='revenuesplitrecord',
            constraint=models.CheckConstraint(check=models.Q(('amount_wei__gte', 0)), name='collab_revenue_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='collaborationmember',
            constraint=models.UniqueConstraint(fields=('collaboration', 'user'), name='collab_unique_user_per_collaboration'),
        ),
        migrations.AddConstraint(
            model_name='collaborationmember',
            constraint=models.UniqueConstraint(fields=('collaboration', 'wallet_address'), name='collab_unique_wallet_per_collaboration'),
        ),
        migrations.AddConstraint(
            model_name='collaborationmember',
            constraint=models.CheckConstraint(check=models.Q(('split_bps__gte', 1), ('split_bps__lte', 10000)), name='collab_member_split_bps_range'),
        ),
    ]
