# Generated by Django 4.2.7 on 2026-04-04 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collaboration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboration',
            name='media_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CollaborationMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='collaboration/media/%Y/%m/%d/')),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collaboration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='collaboration.collaboration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collaboration_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'collaboration_media',
                'ordering': ['-created_at'],
            },
        ),
    ]
