# Generated by Django 4.2.7 on 2026-04-04 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_step7_blockchain_registration_fields_and_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collaboration', '0002_collaboration_media_count_collaborationmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, default='')),
                ('proposed_split_bps', models.PositiveIntegerField(default=5000)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collaboration', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_request', to='collaboration.collaboration')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_collaboration_requests', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_collaboration_requests', to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaboration_requests', to='works.creativework')),
            ],
            options={
                'db_table': 'collaboration_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='collaborationrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('work', 'requester'), name='uniq_pending_collaboration_request_per_work_requester'),
        ),
        migrations.AddConstraint(
            model_name='collaborationrequest',
            constraint=models.CheckConstraint(check=models.Q(('proposed_split_bps__gte', 1), ('proposed_split_bps__lte', 9999)), name='collab_request_split_bps_range'),
        ),
    ]
