# Generated by Django 4.2.7 on 2026-03-17 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreativeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('text', 'Text'), ('document', 'Document')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING_UPLOAD', 'Pending upload'), ('UPLOADED', 'Uploaded'), ('VALIDATION_FAILED', 'Validation failed'), ('UPLOAD_FAILED', 'Upload failed')], default='PENDING_UPLOAD', max_length=32)),
                ('file', models.FileField(blank=True, null=True, upload_to='works/%Y/%m/%d/')),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creative_works', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'works_creative_work',
                'ordering': ['-created_at'],
            },
        ),
    ]
