# Generated by Django 4.2.7 on 2026-03-17 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creativework',
            name='status',
            field=models.CharField(choices=[('PENDING_UPLOAD', 'Pending upload'), ('UPLOADED', 'Uploaded'), ('VALIDATION_FAILED', 'Validation failed'), ('UPLOAD_FAILED', 'Upload failed'), ('PROCESSING', 'Processing'), ('PROCESSING_COMPLETE', 'Processing complete'), ('PROCESSING_FAILED', 'Processing failed')], default='PENDING_UPLOAD', max_length=32),
        ),
        migrations.CreateModel(
            name='ContentHash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_type', models.CharField(choices=[('sha256', 'SHA-256'), ('perceptual_avg', 'Perceptual average hash (image)'), ('text_normalized', 'Text normalized hash')], max_length=30)),
                ('hash_value', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_hashes', to='works.creativework')),
            ],
            options={
                'db_table': 'works_content_hash',
                'ordering': ['hash_type'],
                'unique_together': {('work', 'hash_type')},
            },
        ),
    ]
