"""
Django settings for creativechain project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from urllib.parse import parse_qs, urlparse
from celery.schedules import crontab
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

try:
    import sentry_sdk
    from sentry_sdk.integrations.celery import CeleryIntegration
    from sentry_sdk.integrations.django import DjangoIntegration
except ImportError:  # pragma: no cover - optional in local/dev if not installed
    sentry_sdk = None
    CeleryIntegration = None
    DjangoIntegration = None

# Load environment variables
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-p2_0_(ktbkgr-8bsas$d4b-m11bkz=y5bc)e&pekzuy__o%^#c')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    
    # Local apps
    'apps.accounts',
    'apps.audit_logs',
    'apps.works',
    'apps.marketplace',
    'apps.licensing',
    'apps.infringement',
    'apps.legal',
    'apps.collaboration',
    'apps.analytics',
]

# Custom user model
AUTH_USER_MODEL = 'accounts.User'

# Password hashing — bcrypt with cost 12 (BCryptSHA256PasswordHasher.rounds defaults to 12)
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',   # fallback for legacy hashes
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'creativechain.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'creativechain.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

import dj_database_url


def _get_required_postgres_url() -> str:
    database_url = os.getenv('DATABASE_URL', '').strip()
    if not database_url:
        raise ImproperlyConfigured('DATABASE_URL is required and must point to PostgreSQL.')

    valid_schemes = ('postgres://', 'postgresql://')
    if not database_url.startswith(valid_schemes):
        raise ImproperlyConfigured('DATABASE_URL must use a PostgreSQL URL scheme.')

    parsed = urlparse(database_url)
    if not parsed.hostname:
        raise ImproperlyConfigured('DATABASE_URL must include a valid PostgreSQL hostname.')

    sslmode = parse_qs(parsed.query).get('sslmode', [''])[0]
    if sslmode != 'require':
        raise ImproperlyConfigured('DATABASE_URL must include sslmode=require for Supabase PostgreSQL.')

    return database_url


def _parse_csv_env(var_name: str) -> list[str]:
    raw_value = os.getenv(var_name, '')
    return [item.strip() for item in raw_value.split(',') if item.strip()]

DATABASES = {
    'default': dj_database_url.config(
        default=_get_required_postgres_url(),
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'
STORAGES = {
    'default': {
        'BACKEND': os.getenv('DJANGO_DEFAULT_FILE_STORAGE', 'django.core.files.storage.FileSystemStorage'),
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'EXCEPTION_HANDLER': 'creativechain.exceptions.creativechain_exception_handler',
    # Step 14: keep global defaults for non-auth endpoints.
    # Auth endpoints use ScopedRateThrottle at the view level.
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/day',
        'auth_login': '10/hour',
        'auth_register': '5/hour',
        'auth_refresh': '120/hour',
    },
}

# JWT Configuration
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# CORS Configuration
CORS_ALLOWED_ORIGINS = _parse_csv_env('CORS_ALLOWED_ORIGINS')

CORS_ALLOW_CREDENTIALS = True

# Redis Configuration
REDIS_URL = os.getenv('REDIS_URL', 'redis://localhost:6379/0')

# Celery Configuration
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Celery Redis SSL Configuration (for Upstash/managed Redis services)
# Automatically detect if using SSL (rediss://) and configure accordingly
if CELERY_BROKER_URL.startswith('rediss://'):
    CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
    CELERY_BROKER_CONNECTION_RETRY = True
    CELERY_BROKER_CONNECTION_MAX_RETRIES = 10

# Blockchain Configuration
POLYGON_AMOY_RPC_URL = os.getenv('POLYGON_AMOY_RPC_URL', os.getenv('POLYGON_MUMBAI_RPC_URL', ''))
POLYGON_AMOY_RPC_FALLBACK_URL = os.getenv(
    'POLYGON_AMOY_RPC_FALLBACK_URL',
    os.getenv('POLYGON_MUMBAI_RPC_URL', ''),
)
BLOCKCHAIN_RPC_REQUEST_TIMEOUT_SEC = float(os.getenv('BLOCKCHAIN_RPC_REQUEST_TIMEOUT_SEC', '10'))
BLOCKCHAIN_RPC_MAX_RETRIES = int(os.getenv('BLOCKCHAIN_RPC_MAX_RETRIES', '2'))
BLOCKCHAIN_RPC_RETRY_BASE_SECONDS = float(os.getenv('BLOCKCHAIN_RPC_RETRY_BASE_SECONDS', '0.5'))
BLOCKCHAIN_RECEIPT_MAX_RETRIES = int(os.getenv('BLOCKCHAIN_RECEIPT_MAX_RETRIES', '8'))
POLYGON_AMOY_EXPLORER_TX_BASE_URL = os.getenv(
    'POLYGON_AMOY_EXPLORER_TX_BASE_URL',
    'https://amoy.polygonscan.com/tx/',
)
CONTRACT_IP_REGISTRY_ADDRESS = os.getenv('CONTRACT_IP_REGISTRY_ADDRESS', '')
CONTRACT_LICENSE_AGREEMENT_ADDRESS = os.getenv('CONTRACT_LICENSE_AGREEMENT_ADDRESS', '')
CONTRACT_COLLABORATIVE_WORK_ADDRESS = os.getenv('CONTRACT_COLLABORATIVE_WORK_ADDRESS', '')

# Infringement Detection (Step 10)
INFRINGEMENT_MATCH_THRESHOLD = float(os.getenv('INFRINGEMENT_MATCH_THRESHOLD', '0.65'))
INFRINGEMENT_SEVERITY_MEDIUM_THRESHOLD = float(os.getenv('INFRINGEMENT_SEVERITY_MEDIUM_THRESHOLD', '0.70'))
INFRINGEMENT_SEVERITY_HIGH_THRESHOLD = float(os.getenv('INFRINGEMENT_SEVERITY_HIGH_THRESHOLD', '0.85'))
INFRINGEMENT_SEVERITY_CRITICAL_THRESHOLD = float(os.getenv('INFRINGEMENT_SEVERITY_CRITICAL_THRESHOLD', '0.95'))
INFRINGEMENT_ENABLE_IMAGE_PHASH = os.getenv('INFRINGEMENT_ENABLE_IMAGE_PHASH', 'False') == 'True'
INFRINGEMENT_ENABLE_AUDIO_MFCC = os.getenv('INFRINGEMENT_ENABLE_AUDIO_MFCC', 'False') == 'True'
INFRINGEMENT_ENABLE_TEXT_SEMANTIC = os.getenv('INFRINGEMENT_ENABLE_TEXT_SEMANTIC', 'False') == 'True'
INFRINGEMENT_DAILY_SCAN_HOUR_UTC = int(os.getenv('INFRINGEMENT_DAILY_SCAN_HOUR_UTC', '0'))
INFRINGEMENT_DAILY_SCAN_MINUTE_UTC = int(os.getenv('INFRINGEMENT_DAILY_SCAN_MINUTE_UTC', '0'))
INFRINGEMENT_NOTIFICATION_COOLDOWN_MINUTES = int(os.getenv('INFRINGEMENT_NOTIFICATION_COOLDOWN_MINUTES', '10'))
INFRINGEMENT_PUBLIC_SCAN_ENABLED = os.getenv('INFRINGEMENT_PUBLIC_SCAN_ENABLED', 'True') == 'True'
INFRINGEMENT_PUBLIC_SCAN_MAX_RESULTS = int(os.getenv('INFRINGEMENT_PUBLIC_SCAN_MAX_RESULTS', '12'))
INFRINGEMENT_PUBLIC_SCAN_TIMEOUT_SEC = float(os.getenv('INFRINGEMENT_PUBLIC_SCAN_TIMEOUT_SEC', '10'))

CELERY_BEAT_SCHEDULE = {
    'infringement-daily-simulated-scan': {
        'task': 'infringement.daily_simulated_scan',
        'schedule': crontab(
            hour=INFRINGEMENT_DAILY_SCAN_HOUR_UTC,
            minute=INFRINGEMENT_DAILY_SCAN_MINUTE_UTC,
        ),
    },
}

# IPFS Configuration
PINATA_API_KEY = os.getenv('PINATA_API_KEY', '')
PINATA_SECRET_KEY = os.getenv('PINATA_SECRET_KEY', '')

# Email Configuration
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = 'smtp.sendgrid.net'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'apikey'
EMAIL_HOST_PASSWORD = os.getenv('SENDGRID_API_KEY', '')
DEFAULT_FROM_EMAIL = os.getenv('EMAIL_FROM', 'noreply@creativechain.com')

# Monitoring (Step 15)
SENTRY_DSN = os.getenv('SENTRY_DSN', '').strip()
SENTRY_ENVIRONMENT = os.getenv('SENTRY_ENVIRONMENT', 'production')
SENTRY_TRACES_SAMPLE_RATE = float(os.getenv('SENTRY_TRACES_SAMPLE_RATE', '0.1'))

if SENTRY_DSN and len(SENTRY_DSN) > 0 and sentry_sdk:
    try:
        sentry_sdk.init(
            dsn=SENTRY_DSN,
            integrations=[DjangoIntegration(), CeleryIntegration()],
            environment=SENTRY_ENVIRONMENT,
            traces_sample_rate=SENTRY_TRACES_SAMPLE_RATE,
            send_default_pii=False,
        )
    except Exception:  # pragma: no cover - handle Sentry init errors gracefully
        pass  # Sentry initialization failed, continue without it

